services:
  curator:
    build:
      context: extensions/curator/
    container_name: curator
    init: true
    volumes:
      - ./extensions/curator/config/curator.yml:/.curator/curator.yml:ro,Z
      - ./extensions/curator/config/delete_log_files_curator.yml:/.curator/delete_log_files_curator.yml:ro,Z
      - ./extensions/curator/config/delete_logs_files_curator.yml:/.curator/delete_logs_files_curator.yml:ro,Z
      - ./extensions/curator/config/delete_logstash_files_curator.yml:/.curator/delete_logstash_files_curator.yml:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - yan
    depends_on:
      - elasticsearch
    restart: unless-stopped
