services:
  fleet-server:
    build:
      context: extensions/fleet/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: fleet-server
    hostname: fleet-server
    ports:
      - 8220:8220
    volumes:
      - fleet-server:/usr/share/elastic-agent/state:Z
    environment:
      FLEET_SERVER_ENABLE: "1"
      FLEET_SERVER_INSECURE_HTTP: "1"
      FLEET_SERVER_HOST: "0.0.0.0"
      FLEET_SERVER_POLICY_ID: "fleet-server-policy"
      KIBANA_FLEET_SETUP: "1"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - yan
    depends_on:
      - elasticsearch
      - kibana
    restart: unless-stopped

volumes:
  fleet-server:
